### ISSUE TITLE
 验证码截图问题

### ISSUE THREAD

**Issue by Johums** [LetSpidersEasier/crack_geetest#1]
验证码在截图时候， 发现截图的东西不对 一直验证失败
环境 为mac，python2.7
![8c6ffb52417a43d0bf2105456d0ef56e](https://cloud.githubusercontent.com/assets/16803696/21095517/ce8bbf92-c096-11e6-9a09-a12704c733b4.png)

**Comment by iYgnohZ** [comment]
可能是网站更新了，这个是一个月前写的，我抽时间更新下。

**Comment by Johums** [comment]
好滴 坐等解决

**Comment by nikon321** [comment]
同问～
